### ISSUE TITLE
example is needed 

### ISSUE THREAD

**Issue by unnir** [lki1354/python3-LTspice#1]
Hi,

it would be really great to have one-two examples!

Best,
Paddy

**Comment by lki1354** [comment]
Hi,

Very apologize for my very very late reply. 
Sorry that I didn't reply and add some examples early.
Now I updated the tool and also some examples. I created the tool for my Bachelor Thesis and afterward, I didn´t really use it. But now I worked again with it.

Regards,
Lukas
